AWSTemplateFormatVersion: '2010-09-09'
Description: Start-stop service
Parameters:
  CodeSourceBucket:
    Description: Bucket with source. Have to be in same region.
    Type: String
  CodeSourceKey:
    Description: Key in the bucket with source.
    Type: String

Resources:
  StartStopIAMEC2Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: ['ec2:Describe*', 'ec2:StartInstances', 'ec2:StopInstances']
            Effect: Allow
            Resource: ['*']
            Sid: StartstopEc220161015
        Version: '2012-10-17'
      PolicyName: StartStopEC2
      Roles:
        - !Ref StartStopIAMRole
  StartStopIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
        Version: '2012-10-17'
      ManagedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole']
      Path: /
  StartStopService:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeSourceBucket
        S3Key: !Ref CodeSourceKey
      Description: start and stop your resources during nights and weekends
      Handler: startstop.lambda_handler
      MemorySize: 128
      Role: !GetAtt [StartStopIAMRole, Arn]
      Runtime: python2.7
      Timeout: 5
